### ISSUE TITLE
Great repo to help in the transition but ...

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/vulcan-meteor-next-transition#1]
Hi @eric-burel ,

This repo is great but not very convenient for people unfamiliar with VulcanJS ecosystem.

I suggest to put all codes inside the front end and back end folders directly instead users having to get them from the other 2 repos. I know doing so may lead to code not sync with the original repos but it's really making it more convenient.

Thank You
Adalidda

**Comment by eric-burel** [comment]
Yeah it's kinda automated actually, git is creating submodules when it detects you are using already existing frameworks. Is that a blocker to you? In which way do you find it inconvenient?
Note that there will be a 3rd folder as well in the next iteration, "common", to store shared schemas.

**Comment by adalidda** [comment]
Thank You @eric-burel. This is really a great move. I already used VulcanJS as a backend for Next JS but also for our Flutter Apps and it works great.

You should think about setting a cloud service similar to Hasura or Strapi in order to better facilitate the adoption of VulcanJS on a large scale.

Adalidda

**Comment by eric-burel** [comment]
Glad that you managed to use it with other technologies! I'd be glad to see what you have done so far.

Yeah we will definitely invest into more interesting features sooner or later.

I am closing th issue in the meantime, I've updated the readme with better git submodules so we can get the code easily.
